// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecureSend.Infrastructure.EF.Context;

#nullable disable

namespace SecureSend.Infrastructure.EF.Migrations
{
    [DbContext(typeof(SecureSendDbWriteContext))]
    partial class SecureSendDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("upload")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecureSend.Domain.Entities.SecureSendUpload", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("_expiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("ExpiryDate");

                    b.Property<bool>("_isViewedl")
                        .HasColumnType("bit")
                        .HasColumnName("IsViewed");

                    b.Property<DateTime>("_uploadDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("UploadDate");

                    b.HasKey("Id");

                    b.ToTable("SecureUploads", "upload");
                });

            modelBuilder.Entity("SecureSend.Domain.Entities.SecureSendUpload", b =>
                {
                    b.OwnsMany("SecureSend.Domain.ValueObjects.SecureSendFile", "_files", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("ContentType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FileName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<Guid>("SecureSendUploadId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("SecureSendUploadId");

                            b1.ToTable("UploadedFiles", "upload");

                            b1.WithOwner()
                                .HasForeignKey("SecureSendUploadId");
                        });

                    b.Navigation("_files");
                });
#pragma warning restore 612, 618
        }
    }
}
