// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SecureSend.Infrastructure.EF.Context;

#nullable disable

namespace SecureSend.Infrastructure.Migrations
{
    [DbContext(typeof(SecureSendDbReadContext))]
    partial class SecureSendDbReadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("upload")
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SecureSend.Infrastructure.EF.Models.SecureUploadsReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsViewed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SecureUploads", "upload");
                });

            modelBuilder.Entity("SecureSend.Infrastructure.EF.Models.UploadedFilesReadModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SecureSendUploadId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SecureSendUploadId");

                    b.ToTable("UploadedFiles", "upload");
                });

            modelBuilder.Entity("SecureSend.Infrastructure.EF.Models.UploadedFilesReadModel", b =>
                {
                    b.HasOne("SecureSend.Infrastructure.EF.Models.SecureUploadsReadModel", "SecureUpload")
                        .WithMany("Files")
                        .HasForeignKey("SecureSendUploadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SecureUpload");
                });

            modelBuilder.Entity("SecureSend.Infrastructure.EF.Models.SecureUploadsReadModel", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
